### ISSUE TITLE
After Update Bamboo  no plugin with key artifactoryGradleTask

### ISSUE THREAD

**Issue by DanielWeeber** [jfrog/bamboo-artifactory-plugin#139]
**Describe the bug**
After update of our bamboo we cannot run builds with artifact download/gradle anymore

**To Reproduce**
Just run the build which was working before

**Expected behavior**
A working build ;)

**Screenshots**
"Could not execute Task '' no plugin with key 'org.jfrog.bamboo.bamboo-artifactory-plugin:artifactoryGradleTask'
<img width="1238" alt="Bildschirmfoto 2021-02-03 um 18 16 47" src="https://user-images.githubusercontent.com/2935130/106783830-fee60580-664b-11eb-965b-ab3e2131b12f.png">

**Versions**
- Bamboo Artifactory plugin version: 3.2.1
- Bamboo operating system: Ubuntu 18
- Artifactory Version: 5.4.6

**Additional context**
Task is being run on remote agents, but not elastic/ec2. Just linux agents.

**Comment by yahavi** [comment]
@DanielWeeber,
Thanks for reporting this issue!

As it looks like, the plugin is not installed on your agent. This may occur due to many reasons. Please try to reinstall the plugin and check the agent's logs.

For example, one possible reason is the lack of memory in the agent. If you see errors such as:

    INFO | jvm 1 | 2020/11/10 11:12:36 | 2020-11-10 11:12:36,120 ERROR [remoteEventRebroadcasterMessageListenerContainer-1] [ScanningPluginLoader] Unable to deploy plugin 'org.jfrog.bamboo.bamboo-artifactory-plugin' from 'Unit: /Users/yahavi/bamboo-agent-home/plugins/user-installed/plugin_8527020839401694412_bamboo-artifactory-plugin-3.1.0.jar (1604999532000)'.
    INFO | jvm 1 | 2020/11/10 11:12:36 | 2020-11-10 11:12:36,121 ERROR [remoteEventRebroadcasterMessageListenerContainer-1] [ScanningPluginLoader] Because of the following exception:
    INFO | jvm 1 | 2020/11/10 11:12:36 | java.lang.OutOfMemoryError: GC overhead limit exceeded

That means your agent has insufficient heap size. I'd recommend on the resolution in this guide: https://confluence.atlassian.com/bamkb/outofmemory-errors-in-bamboo-server-or-in-remote-agent-307038120.html

Please let me know if it helped.

**Comment by DanielWeeber** [comment]
I have to install the Plugin on the Agent? How?

**Comment by yahavi** [comment]
@DanielWeeber 
The Bamboo plugin manager automatically installs the plugins on the agent. Manually installation on the agent is not needed.
Please make sure to have enough RAM allocated in the agent and reinstall the plugin in the master.

**Comment by DanielWeeber** [comment]
I increased Heap size and Plugin installed successfully. Thank you

Now it fails with a different error

Any tips?
`FAILURE: Build failed with an exception.

* Where:
Initialization script '/home/bamboo-agent/bamboo-agent-home/temp/artifactory.init.script5037685123225946796gradle' line: 23

* What went wrong:
Failed to apply plugin [class 'org.jfrog.gradle.plugin.artifactory.ArtifactoryPlugin']
> No signature of method: org.gradle.api.internal.tasks.RealizableTaskCollection.configureEach() is applicable for argument types: (org.jfrog.gradle.plugin.artifactory.ArtifactoryPluginBase$_addModuleInfoTask_closure2) values: [org.jfrog.gradle.plugin.artifactory.ArtifactoryPluginBase$_addModuleInfoTask_closure2@576735c8]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s`

**Comment by yahavi** [comment]
@DanielWeeber 
What is your Gradle version?

IMO the root cause of this is a very old Gradle version.
RealizableTaskCollection.configureEach() introduced 3 years ago in Gradle 4.9:
https://github.com/gradle/gradle/commit/bd284b62745b1583c3e11db73c3f35c1cbf759b9#diff-b5dff85db66c20ce00cea0a310ac5071c0a83745119bb37b0f400e110e5f489fR154.

The minimal supported Gradle version in our plugins is 4.10 or above.

**Comment by DanielWeeber** [comment]
Thank you very much. Working just fine.
