### ISSUE TITLE
Log4j vulnerable 

### ISSUE THREAD

**Issue by nhatia** [jfrog/bamboo-artifactory-plugin#162]
Hi Team,

We are using your Plugin ‘Bamboo Artifactory Plugin’ in our organization. Can you please confirm if it is vulnerable for the recent log4j vulnerability CVE-2021-44228 ?

https://confluence.atlassian.com/security/multiple-products-security-advisory-log4j-vulnerable-to-remote-code-execution-cve-2021-44228-1103069934.html

Regards,
Neeraj Bhatia

**Comment by yahavi** [comment]
@nhatia,
The short answer is no.

In 3.2.4 and below, we used log4j 1.17.10, which is NOT vulnerable to CVE-2021-44228.
Since the latest release 3.2.5, to be on the safe side, [we started to use](https://github.com/jfrog/bamboo-artifactory-plugin/pull/161) the latest version of log4j-core 2.16.0, which is NOT vulnerable for CVE-2021-44228. 

Please let us know if you have any more concerns about it.
