### ISSUE TITLE
How can i build Nuget Packages from Bamboo into JFrog

### ISSUE THREAD

**Issue by emotdk** [jfrog/bamboo-artifactory-plugin#181]
I have installed JFrog Artifactory. Everything works great. My question is, how to build nuget packages directly in JFrog from Bamboo? Everything I have tried has not worked and unfortunately there is no documentation on the internet. 
How do I proceed?
1. create a plan in Bamboo
2. i create in Bamboo in the default job a task ,,Artifactory NuGet".
3. there I have to enter push/restore, paths, executable etc.. 

Everything I have tried has not helped. Does anyone know more?

Thanks in advance!

![github](https://user-images.githubusercontent.com/104839802/167872178-dfa0df41-0288-4166-8119-bce7383b6f20.PNG)

**Comment by holle** [comment]
Hi @emotdk,
as mentioned in my first post, I ave real clue about dot.net or nuget ....

But apart from that the following is true:
Whatever machine you use to run the Bamboo Build Agent on (since Bamboo 8 only remote agents are supported), *that* agent has to be able to find the nuget.exe in it's path at the location you specified in the "Server Capabilities" section.
Regarding JFrog itself -- I have no idea ;-)

* What does the Build log say, especially regarding the last task and it's successes or failures?
* Can you define an "Artifact" (in the Jobs Artifacts Tab) in Atlassian Bamboo matching the file you want to upload to Artifactory in order to check whether Bamboo actually finds it? If Bamboo does not find the file(s) you want to publish to Artifactory then something else is wrong, maybe simply the path to the resulting file or something ....
Cheers,
Holger

**Comment by emotdk** [comment]
So let me explain everything in detail.

I have JFrog installed on one server. And Bamboo is running on another server. The connection test is successful. Bamboo can access JFrog Artifactory.

I think it doesn't matter if you know nuget or not, because I also don't know it  :D . I work as a DevOps, i just have to make bamboo automatically build nuget packages in JFrog.

**1. on a plan in Bamboo I go to Configure Plan -> Build -> Task**

**2. i create a task -> Artifactory Nuget <-.** 

![1](https://user-images.githubusercontent.com/104839802/168102137-fa2de84d-f46d-4741-834b-7c93466c6751.PNG)

![2](https://user-images.githubusercontent.com/104839802/168102243-106b2b3d-4ab9-4bb2-96c9-2257bbdbef77.PNG)


**3. i create an executable. The Nuget.exe Path for the Job (which is on the Bamboo server)**

![3](https://user-images.githubusercontent.com/104839802/168102357-bfeb8ab4-65cd-4c41-b1ed-322d7d77c04d.PNG)

**4. i save this and run the job**

**5. the build was successful. The log says this:**

![4](https://user-images.githubusercontent.com/104839802/168102400-d97023c8-7a22-4b8d-997b-25c018c5fbd9.PNG)

**The Log**
simple	12-May-2022 16:38:44	Build Software Deployment Testing - Nuget.Testing - Default Job #14 (SDT-NUG-JOB1-14) started building on agent Build agent 03, bamboo version: 8.1.2
simple	12-May-2022 16:38:44	
simple	12-May-2022 16:38:45	Build working directory is D:\bamboo-home\local-working-dir\SDT-NUG-JOB1
simple	12-May-2022 16:38:45	Executing build Software Deployment Testing - Nuget.Testing - Default Job #14 (SDT-NUG-JOB1-14)
simple	12-May-2022 16:38:45	Starting task 'Checkout Default Repository' of type 'com.atlassian.bamboo.plugins.vcs:task.vcs.checkout'
simple	12-May-2022 16:38:45	Checking out into D:\bamboo-home\local-working-dir\SDT-NUG-JOB1
simple	12-May-2022 16:38:45	Updating source code to revision: 55dd00f9d946a45317c2f49a1d596c4d4549158b
simple	12-May-2022 16:38:45	Fetching 'refs/heads/develop' from 'ssh://git@svbb0045:7999/adt/nuget.testing.git'.
simple	12-May-2022 16:38:45	Warning: Permanently added '[127.0.0.1]:1836' (RSA) to the list of known hosts.
simple	12-May-2022 16:38:45	Checking out revision 55dd00f9d946a45317c2f49a1d596c4d4549158b.
simple	12-May-2022 16:38:45	Already on 'develop'
simple	12-May-2022 16:38:45	Your branch is up to date with 'origin/develop'.
simple	12-May-2022 16:38:46	Updated source code to revision: 55dd00f9d946a45317c2f49a1d596c4d4549158b
simple	12-May-2022 16:38:46	Finished task 'Checkout Default Repository' with result: Success
simple	12-May-2022 16:38:46	Running pre-build action: VCS Version Collector
simple	12-May-2022 16:38:46	Running pre-build action: Artifactory Release Staging
simple	12-May-2022 16:38:46	Running pre-build action: Build Log Labeller Pre Build Action
command	12-May-2022 16:38:46	Substituting variable: ${bamboo.buildNumber} with 14
command	12-May-2022 16:38:46	Substituting variable: ${bamboo.buildPlanName} with Software Deployment Testing - Nuget.Testing - Default Job
simple	12-May-2022 16:38:46	Starting task 'build-package' of type 'org.jfrog.bamboo.bamboo-artifactory-plugin:artifactoryNugetTask'
simple	12-May-2022 16:38:47	Usage info sent successfully.
simple	12-May-2022 16:38:47	Finished task 'build-package' with result: Success
simple	12-May-2022 16:38:47	Running post build plugin 'NCover Results Collector'
simple	12-May-2022 16:38:47	Running post build plugin 'Artifact Copier'
simple	12-May-2022 16:38:47	Running post build plugin 'Artifactory Release Management Staging'
simple	12-May-2022 16:38:47	Running post build plugin 'Artifactory Build Info Copier'
simple	12-May-2022 16:38:47	Running post build plugin 'Artifactory Gradle Properties Info Copier'
simple	12-May-2022 16:38:47	Running post build plugin 'npm Cache Cleanup'
simple	12-May-2022 16:38:47	Running post build plugin 'Build Results Label Collector'
simple	12-May-2022 16:38:47	Running post build plugin 'Clover Results Collector'
simple	12-May-2022 16:38:47	Running post build plugin 'Docker Container Cleanup'
simple	12-May-2022 16:38:47	Finalising the build...
simple	12-May-2022 16:38:47	Stopping timer.
simple	12-May-2022 16:38:47	Build SDT-NUG-JOB1-14 completed.
simple	12-May-2022 16:38:47	Running on server: post build plugin 'NCover Results Collector'
simple	12-May-2022 16:38:47	Running on server: post build plugin 'Build Hanging Detection Configuration'
simple	12-May-2022 16:38:47	Running on server: post build plugin 'Build Labeller'
simple	12-May-2022 16:38:47	Running on server: post build plugin 'Clover Delta Calculator'
simple	12-May-2022 16:38:47	Running on server: post build plugin 'Maven Dependencies Postprocessor'
simple	12-May-2022 16:38:47	All post build plugins have finished
simple	12-May-2022 16:38:47	Generating build results summary...
simple	12-May-2022 16:38:47	Saving build results to disk...
simple	12-May-2022 16:38:47	Store variable context...
simple	12-May-2022 16:38:47	Indexing build results...
simple	12-May-2022 16:38:47	Finished building SDT-NUG-JOB1-14.

6. I go to JFrog, but there is no Nuget Package in my Nuget-local Repository

PS: I am new in Bamboo and JFrog

**Comment by holle** [comment]
HI @emotdk,

your logfile shows that the task actually "sends" something to the Artifactory:
> simple	12-May-2022 16:38:46	Starting task 'build-package' of type 'org.jfrog.bamboo.bamboo-artifactory-plugin:artifactoryNugetTask'
> simple	12-May-2022 16:38:47	Usage info sent successfully.

but this could also only be the "Meta" build information.

The question is, does your "normal" build generate any file(s) matching the pattern `*.nupkg` as shown in the screenshot?
Is it possible the file(s) are located in a subdirectory?
Is it possible you are missing an MSBuild or something *before* the actual nuget Artifactory task?

When I am using Bamboo to build and upload artifacts I always have three tasks:
* Source Code Checkout
* Run Maven (compiles Java Code) -> this produces my artifacts in target/*.jar
* Run Artifactory "Deploy" job to publish the  target/*.jar file(s) into my artifactory.

Here is a more sophisticated build job configuration with all tasks in configured on my side (building Java :-) )

![Build Configuration](https://user-images.githubusercontent.com/219809/168231551-aba280b7-4256-415b-bb9f-78c3df4d435c.png)

* Sonar is actually a code quality check, so this does not apply for you.
* I have two separate Artifactory Tasks because my Develop branch and my Release Branches are uploaded into different Artifactory Repositories ;-)

Does this help?
Cheers,
Holger

**Comment by emotdk** [comment]
Got it working.
The error was I specified a link in the deployment path. There you only have to specify a folder on the server where it caches the stuff. I didn't need a new Nuget.exe on the JFrog server, I used the one from the bamboo server. 
Then I ran that as a test, and voila it works. Now I also see all the Nuget packages on the JFrog interface.

<img width="1226" alt="nuget result" src="https://user-images.githubusercontent.com/104839802/170044253-392fbeba-f4d4-4111-b7e8-8d3c68072de8.PNG">

And here are the results on the Artifactory GUI

<img width="1887" alt="2nuget result" src="https://user-images.githubusercontent.com/104839802/170045084-a0e7d467-8225-4af8-ad27-510bbddc36ff.PNG">
