### ISSUE TITLE
Artifactory plugin 3.2.10 for Bamboo does not work in Bamboo 9.0

### ISSUE THREAD

**Issue by nightwww1** [jfrog/bamboo-artifactory-plugin#190]
To Reproduce
Upgrade Bamboo to version 9.0

Expected behavior
Artifactory plugin 3.2.10 for Bamboo successfully start up in Bamboo 9.0

Versions

Bamboo Artifactory plugin version: 3.2.10
Bamboo operating system: Red_Hat 7.9
Artifactory Version: 7.41.4 rev 74104900 
Bamboo Version: 9.0.0
Java: oracle jdk -11.0.16.1

**Comment by Sven-O** [comment]
I have a similar problem but will file a separate ticket as it is somewhat different behavior. I upgraded to Bamboo 9.0.1 with the Artifactory add-on 3.2.9. It is set to incompatible and cant even be enabled and used. When I try to add  the add-on from the UI, it does not show up.

**Comment by eyalbe4** [comment]
The Bamboo Artifactory Plugin doesn't Support Bamboo 9.0. The reason for this is that Bamboo 9.0 is built on Atlassian Data Center's infrastructure, and the existing Bamboo Artifactory Plugin code base isn't compatible with it.
We do plan to create a new native plugin compatible with Data Center in the future, but re-engineering the existing plugin to work with Data Center doesn't seem like the best way to go. One way to integrate Data Center with the JFrog Platform today is by using JFrog CLI.

**Comment by tibormarchynzoom** [comment]
> The Bamboo Artifactory Plugin doesn't Support Bamboo 9.0. The reason for this is that Bamboo 9.0 is built on Atlassian Data Center's infrastructure, and the existing Bamboo Artifactory Plugin code base isn't compatible with it. We do plan to create a new native plugin compatible with Data Center in the future, but re-engineering the existing plugin to work with Data Center doesn't seem like the best way to go. One way to integrate Data Center with the JFrog Platform today is by using JFrog CLI.

But we need fix ASAP, not waiting years till new plugin exists. With hundreds of plans using Artifactory Bamboo plugin is impossible to change it to CLI!!!!

**Comment by eyalbe4** [comment]
I completely understand @tibormarchynzoom the issue, but following the changes introduced by DataCenter, it practically makes no sense to adapt the existing Bamboo Artifactory Plugin to it. Bamboo 9 isn't just another Bamboo release.

**Comment by cmccoy98** [comment]
Is there an ETA on a new release?

**Comment by trmcclain** [comment]
Is there even some kind of pre-release test version that can be used in the meantime?

**Comment by Sven-O** [comment]
Does not look that there are any plans to provide this add-on in the near future. Like several here its a problem for my organization as well, with hundreds of CICD pipelines using this add-on. On the suggestions to use Jfrog CLI, I want to say that the add-on is not necessarily only used for pushing artifacts to Artifactory. My organization is for example using the Artifactory Maven 3 task, which builds maven, resolves dependencies, as well as pushes to Artifactory, as well as using the Maven release . process that is built in to the add. In addition, there are several other tasks as well in the Artifactory add-on, providing more functionality than only pushing artifacts. I am blocked from upgrading Bamboo at the moment since to do so, I will need to find a solution to the hundreds of pipelines. Without the add-on, I have to replace add-on tasks in hundreds of build plans and deployment projects. But first, I also have to figure out which build plans uses the Artifactory add-ons. Then document a manual process for replacing the one add-on task with multiple other tasks (build, dependency resolution, deploy), or come up with an automated process to replace those add-on tasks with whatever we come up with.

**Comment by eyalbe4** [comment]
Following additional work and discussions, we started working on a modified version of the existing Bamboo Artifactory Plugin that will work with Bamboo 9. The solution isn't ideal, and we are also working on a new plugin and completely different plugin for DataCenter, but it will provide a solution that will allow upgrading to Bamboo 9 for now. We'll share an additional updates here soon.

**Comment by Sven-O** [comment]
> Following additional work and discussions, we started working on a modified version of the existing Bamboo Artifactory Plugin that will work with Bamboo 9. The solution isn't ideal, and we are also working on a new plugin and completely different plugin for DataCenter, but it will provide a solution that will allow upgrading to Bamboo 9 for now. We'll share an additional updates here soon.

Thanks, sounds good. Any idea for when it could be available? Weeks, Months? I dont want to rush anything, but I need to upgrade Bamboo to 9.1 for security remediation reasons and it cant wait for to long.

**Comment by eyalbe4** [comment]
@Sven-O,
We'll get a working release out by February 14th, but possibly sooner. We'll keep the discussion here up to date.

**Comment by tibormarchynzoom** [comment]
@eyalbe4 Great. Can you please explain in detail why there is needed to rewrite this addon for DataCenter from scratch? Why you just can't updating current one?

**Comment by eyalbe4** [comment]
@tibormarchynzoom,

We ended up working on two seperate activities -

1. Update the code of the existing Artifactory Plugin, so that it is compatible with Bamboo 9. The plugin will work properly when installed on Bamboo 9, but will not be compatible with DataCenter. This is because of the [requirements for DataCenter Plugins](https://developer.atlassian.com/platform/marketplace/dc-apps-performance-toolkit-user-guide-bamboo/), which this plugin will not be able to meet. We're hoping that the Atlassian Marketplace will accept the new plugin version, without having to meet those requirements.

2. We're creating a smarter and leaner plugin that will rely heavily on JFrog CLI. We believe it can be built in a way that will meet the DataCenter plugins requirements. This plugin however will be fundamentally different from the Artifactory Plugin. It'll use a more generic approach for tasks, and will allow for new functionality that isn't supported by the Artifactory Plugin, while making its maintenance more sustainable.

**Comment by Sven-O** [comment]
Will the changes support Bamboo 9+ or only 9.0.1?  e.g. 9.1.1 which is the latest Bamboo version.
I see a reference to Bamboo 9.0.1 in the pom file.

**Comment by RobiNino** [comment]
Hi @nightwww1 @Sven-O @tibormarchynzoom @cmccoy98 @trmcclain 
Bamboo Artifactory plugin version 3.3.0 was just released and is compatible with Bamboo 9.2.1.
We'd appreciate your feedback for it.
Thank you for your patience.

**Comment by Sven-O** [comment]
Greatly appreciated. 
We will test it out ASAP.

**Comment by Sven-O** [comment]
Work for me with Bamboo 9.1.1
Very much appreciated. I dont have to change 100s of build plans.

**Comment by mcgit1982** [comment]
will it be possible to share some dates when JFrog Artifactory Plugin for Bamboo will be available for Bamboo Datacenter edition?

**Comment by eyalbe4** [comment]
@mcgit1982,
We do not intend for Bamboo Artifactory Plugin to be compatible with Bamboo DataCenter edition. The requirements set for compatibility with DataCnter do not allow this plugin to comply. We plan to introduce a different plugin that will be compatible with those requirements, but this plugin will be functionality different and therefore will not support migration of data from the Artifactory Plugin.

**Comment by Sven-O** [comment]
> will it be possible to share some dates when JFrog Artifactory Plugin for Bamboo will be available for Bamboo Datacenter edition?

I also would like to know ETA for the redesigned Artifactory addon. My organization is about to migrate to data center and I want to avoid having to create our own addon.

**Comment by SvenolovL** [comment]
Did the plan to create a different plugin for Bamboo Datacenter not materialize? WE still have status incompatible when using the plugin with Bamboo Datacenter version 9.6.0 it still say "Incompatible"

**Comment by eyalbe4** [comment]
@SvenolovL,
See the message posted [here](https://github.com/jfrog/bamboo-artifactory-plugin/issues/205#issuecomment-1872838383)

**Comment by RobiNino** [comment]
Hi all,

There are two plugins that are available today:
* [Artifactory Bamboo Plugin](https://jfrog.com/help/r/jfrog-integrations-documentation/bamboo-artifactory-plug-in)
* [JFrog Bamboo Plugin](https://github.com/jfrog/bamboo-jfrog-plugin)

The Artifactory Bamboo Plugin is an old legacy plugin that was created many years ago. This plugin will most likely receive no new features or improvements.
The JFrog Bamboo Plugin is a new next-gen plugin, that unlike the older plugin, utilizes JFrog CLI, and therefore continuously improving by inheriting new features and functionality added to JFrog CLI. This plugin is simpler, more stable and already supports significantly more functionality than the older plugin.
Both plugins can be installed and used on the same Bamboo or DataCenter platform, and can be used side by side.
Although the DataCenter platform labels the two plugins as incompatible, both are fully supported by JFrog, and are working properly on Atlassian DataCenter.
