### ISSUE TITLE
Bamboo 6.7 not compatible 

### ISSUE THREAD

**Issue by lodown** [jfrog/bamboo-artifactory-plugin#66]
Looks like the latest version of Bamboo (6.7.x) does not want to play nice with the latest release of the plugin.    The add-on page lists the plugin an incompatible.

**Comment by adusak** [comment]
We are also having this issue. Its funny I wrote a review on the plugin on Atlassian marketplace which got a prompt response unlike this issue on Github which is recommended in the review response.

**Comment by eyalbe4** [comment]
@lodown and @adusak,
The Bamboo Artifactory Plugin is fully tested for compatibility with the version of Bamboo that is current when the plugin is released. When a new version of Bamboo is released, the Marketplace lists the Bamboo Artifactory Plugin as incompatible, however, since we regularly update the plugin it is likely to maintain compatibility with patch or minor version upgrades of Bamboo. 
Please use the compatibility matrix in the [Bamboo Artifactory Plugin User Guide](https://www.jfrog.com/confluence/display/RTF/Bamboo+Artifactory+Plug-in)
In any case, we do recommend testing new Bamboo and plugins releases on a staging environment before upgrading the production environment.

**Comment by lodown** [comment]
I was in the situation with an old version of the plugin when upgrading Bamboo.   So after the upgrade, Bamboo does not allow updating the plugin directly from the add-on screen due to being "incompatible".  I needed to upgrade to get the fix when deploying to artifactory.

My workaround was to download the jar directly from the atlassian marketplace and using the upload plugin feature.  This allowed me to upgrade successfully.  

I understand the next version of the plugin will have the metadata to indicate the support of the latest version of bamboo.    So the status in Bamboo will be fixed soon.

My workaround solved the issue I was having, and the current plugin version seems to be working on 6.7.1, so I will close this issue.
